--
-- PostgreSQL database dump
--

\restrict bkpx7y5b7gxmDNhz7NQp7QOoeWZX9bjYoorVD4wmDelwp7Y9yPQ2pH0RjmAZAPA

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2026-09-02 12:40:20

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 41502)
-- Name: blog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.blog (
    id_blog bigint NOT NULL,
    content text,
    created_at timestamp(6) without time zone,
    state character varying(255),
    title character varying(255),
    updated_at timestamp(6) without time zone,
    version bigint,
    id_category bigint,
    id_user bigint,
    CONSTRAINT blog_state_check CHECK (((state)::text = ANY ((ARRAY['ACTIVO'::character varying, 'INACTIVO'::character varying])::text[])))
);


ALTER TABLE public.blog OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 41501)
-- Name: blog_id_blog_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.blog ALTER COLUMN id_blog ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blog_id_blog_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 41512)
-- Name: category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.category (
    id_category bigint NOT NULL,
    categoria character varying(255),
    description character varying(255),
    version bigint
);


ALTER TABLE public.category OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 41511)
-- Name: category_id_category_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.category ALTER COLUMN id_category ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_id_category_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 41521)
-- Name: comment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.comment (
    id_comment bigint NOT NULL,
    comment text,
    created_at timestamp(6) without time zone,
    state character varying(255),
    updated_at timestamp(6) without time zone,
    version bigint,
    blog_id bigint,
    user_id bigint,
    CONSTRAINT comment_state_check CHECK (((state)::text = ANY ((ARRAY['ACTIVO'::character varying, 'INACTIVO'::character varying])::text[])))
);


ALTER TABLE public.comment OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 41520)
-- Name: comment_id_comment_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.comment ALTER COLUMN id_comment ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_id_comment_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 41531)
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id_rol bigint NOT NULL,
    rol character varying(255)
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 41530)
-- Name: roles_id_rol_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id_rol ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_rol_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 41538)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id_user bigint NOT NULL,
    description character varying(255),
    email character varying(255),
    name character varying(255),
    password character varying(255),
    version bigint,
    rol_id bigint
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 41537)
-- Name: users_id_user_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id_user ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_user_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4778 (class 2606 OID 41510)
-- Name: blog blog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog
    ADD CONSTRAINT blog_pkey PRIMARY KEY (id_blog);


--
-- TOC entry 4780 (class 2606 OID 41519)
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id_category);


--
-- TOC entry 4784 (class 2606 OID 41529)
-- Name: comment comment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT comment_pkey PRIMARY KEY (id_comment);


--
-- TOC entry 4786 (class 2606 OID 41536)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id_rol);


--
-- TOC entry 4790 (class 2606 OID 41551)
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- TOC entry 4782 (class 2606 OID 41547)
-- Name: category ukd9r95vgrg3150xra0fhnx0bw1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT ukd9r95vgrg3150xra0fhnx0bw1 UNIQUE (categoria);


--
-- TOC entry 4788 (class 2606 OID 41549)
-- Name: roles ukg00thobnv3twutok8x6furkx1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukg00thobnv3twutok8x6furkx1 UNIQUE (rol);


--
-- TOC entry 4792 (class 2606 OID 41545)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id_user);


--
-- TOC entry 4793 (class 2606 OID 41552)
-- Name: blog fkckiy7jx9dkamj4i4io7bamqif; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog
    ADD CONSTRAINT fkckiy7jx9dkamj4i4io7bamqif FOREIGN KEY (id_category) REFERENCES public.category(id_category);


--
-- TOC entry 4797 (class 2606 OID 41572)
-- Name: users fkgqf6aajl2lwd68xv9ypxpo7ra; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkgqf6aajl2lwd68xv9ypxpo7ra FOREIGN KEY (rol_id) REFERENCES public.roles(id_rol);


--
-- TOC entry 4795 (class 2606 OID 41562)
-- Name: comment fkkap39f76wn135k7ru564fbjb7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT fkkap39f76wn135k7ru564fbjb7 FOREIGN KEY (blog_id) REFERENCES public.blog(id_blog);


--
-- TOC entry 4796 (class 2606 OID 41567)
-- Name: comment fkqm52p1v3o13hy268he0wcngr5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT fkqm52p1v3o13hy268he0wcngr5 FOREIGN KEY (user_id) REFERENCES public.users(id_user);


--
-- TOC entry 4794 (class 2606 OID 41557)
-- Name: blog fksdncac188ptj2knqd1hfam34s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blog
    ADD CONSTRAINT fksdncac188ptj2knqd1hfam34s FOREIGN KEY (id_user) REFERENCES public.users(id_user);


-- Completed on 2026-09-02 12:40:23

--
-- PostgreSQL database dump complete
--

\unrestrict bkpx7y5b7gxmDNhz7NQp7QOoeWZX9bjYoorVD4wmDelwp7Y9yPQ2pH0RjmAZAPA

