spring:
  application:
    name: proyecto-blog

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:false}
    baseline-version: 1
    validate-on-migrate: true

security:
  jwt:
    secret: ${JWT_SECRET}
    issuer: ${JWT_ISSUER}
    access-token-ttl: ${JWT_ACCESS_TOKEN_TTL}

  app:
    bootstrap-admin:
      enabled: ${BOOTSTRAP_ADMIN_ENABLED:false}
      name: ${BOOTSTRAP_ADMIN_NAME:}
      email : ${BOOTSTRAP_ADMIN_EMAIL:}
      password : ${BOOTSTRAP_ADMIN_PASSWORD:}
