CREATE TABLE roles (
    id_rol BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol VARCHAR(255) UNIQUE
);

CREATE TABLE category (
    id_category BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria VARCHAR(255) UNIQUE,
    description VARCHAR(255),
    version BIGINT
);

CREATE TABLE users (
    id_user BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    name VARCHAR(255),
    password VARCHAR(255),
    version BIGINT,
    rol_id BIGINT,
    CONSTRAINT fk_users_role
        FOREIGN KEY (rol_id) REFERENCES roles(id_rol)
);

CREATE TABLE blog (
    id_blog BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT,
    created_at TIMESTAMP(6),
    state VARCHAR(255),
    title VARCHAR(255),
    updated_at TIMESTAMP(6),
    version BIGINT,
    id_category BIGINT,
    id_user BIGINT,
    CONSTRAINT blog_state_check
        CHECK (state IN ('ACTIVO', 'INACTIVO')),
    CONSTRAINT fk_blog_category
        FOREIGN KEY (id_category) REFERENCES category(id_category),
    CONSTRAINT fk_blog_user
        FOREIGN KEY (id_user) REFERENCES users(id_user)
);

CREATE TABLE comment (
    id_comment BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment TEXT,
    created_at TIMESTAMP(6),
    state VARCHAR(255),
    updated_at TIMESTAMP(6),
    version BIGINT,
    blog_id BIGINT,
    user_id BIGINT,
    CONSTRAINT comment_state_check
        CHECK (state IN ('ACTIVO', 'INACTIVO')),
    CONSTRAINT fk_comment_blog
        FOREIGN KEY (blog_id) REFERENCES blog(id_blog),
    CONSTRAINT fk_comment_user
        FOREIGN KEY (user_id) REFERENCES users(id_user)
);